apiVersion: v1
kind: Pod
metadata:
  name: alpaca-test
  labels:
    ver: "2"
    app: alpaca
    env: test
spec:
  replicas: 1
  containers:
    - image: gcr.io/kuar-demo/kuard-amd64:green
      name: kuard
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP