apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpaca-prod-deployment
  labels:
    ver: "1"
    app: alpaca
    env: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: alpaca-prod
  template:
    metadata:
      labels:
        app: alpaca-prod
    spec:
      containers:
        - image: gcr.io/kuar-demo/kuard-amd64:blue
          name: kuard
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP