apiVersion: v1
kind: Pod
metadata:
  name: bandicoot-staging
  labels:
    ver: "2"
    app: bandicoot
    env: staging
spec:
  replicas: 1
  containers:
    - image: gcr.io/kuar-demo/kuard-amd64:green
      name: kuard
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP